# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/worker/worker.go
    binary: worker
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
env_files:
  github_token: 324a3f7dc69aeab7ba8c4f1e93f0db113f35f9ac
