store:
    server: ubvmmgo01:27017
    name: elasticshift
    username: elasticshift
    password: 3l@$t1c$h1ft
    monotonih: true
    timeout: "10s"
    retry: "10s"

logger:
  level: "debug"
  format: "json"

web:
  http: 0.0.0.0:8080
  grpc: 0.0.0.0:9090

identity:
  issuer: http://ubvmide01:8080/identity
  grpc: 127.0.0.1:9090
  id: yyjw66rn2hso6wriuzlic62jiy
  secret: l77r6wixjjtgmo4iym2kmk3jcuuxetj3afnqaw5w3rnl5nu5hehu
  redirect_uri: http://ubvmide01:8080/login/callback
