version: v1.0
projects:
    - app_name: elasticshift
      app_path: /cmd/elasticshift
      app_run: true
      app_bin: true
      app_fmt: true
      app_watcher:
          paths:
              - /
          ignore_paths:
              - vendor
              - bin
          exts:
              - .go
