version: v1.0
projects:
- app_name: main
  app_path: /
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    ignore_paths:
    - vendor
    - bin
    exts:
    - .go
    output:
      cli: true
      file: true