version: v1.0
settings:
  resources:
    output: outputs.log
    log: logs.log
  server:
    enable: true
    open: true
    host: localhost
    port: 5000
projects:
- app_name: esh
  app_path: /
  app_run: true
  app_bin: true
  app_fmt: true
  app_watcher:
    paths:
    - /
    - ../
    ignore_paths:
    - ../vendor
    - ../bin
    exts:
    - .go
    output:
      cli: true
      file: true