# apiVersion: v1
# kind: Service
# metadata:
#   name: minio
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 9000
#       targetPort: 9000
#       protocol: TCP
#   selector:
#     app: minio
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    name: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30080
      name: http
    # - port: 443
    #   nodePort: 30443
    #   name: https
  selector:
    name: minio
