apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  annotations:
    pv.beta.kubernetes.io/gid: "1005"
spec:
  storageClassName: nfs-sc
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /nfs/elasticshift 
    server: 10.0.2.15
    readOnly: false