apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 5
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfsvol
              mountPath: /opt/elasticshift
      volumes:
        - name: nfsvol
          nfs:
            server: 10.10.7.151
            path: /nfs/elasticshift
            readOnly: false