apiVersion: apps/v1
kind: Deployment
metadata:
  name: openjdk
spec:
  selector:
    matchLabels:
      run: openjdk
  replicas: 1
  template:
    metadata:
      labels:
        run: openjdk
    spec:
      containers:
        - name: openjdk
          image: openjdk
          # command: ["wget --continue --output-document worker.sh http://10.10.3.94:9000/downloads/worker.sh && chmod +x worker.sh && ./worker.sh"]          
          command: ["./lab/elasticshift/sys/startup.sh"]
          env:
          - name: SHIFT_HOST
            value: "10.10.5.101"
          - name: SHIFT_PORT
            value: "9101"
          - name: SHIFT_BUILDID
            value: "5b4f15bedc294aad3cfdadbc"
          - name: SHIFT_TEAMID
            value: "5a3a41f08011e098fb86b41f"
          - name: SHIFT_DIR
            value: "/lab/elasticshift"
          - name: WORKER_PORT
            value: "9200"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: nfsvol
              mountPath: /lab/elasticshift
      volumes:
        - name: nfsvol
          nfs:
            server: 10.10.7.151
            path: /nfs/elasticshift
            readOnly: false
