apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  annotations:
    pv.beta.kubernetes.io/gid: "1005"
spec:
  capacity:
    storage: 15Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /nfs/elasticshift 
    server: 10.10.7.151
    readOnly: false