kind: Namespace
apiVersion: v1
metadata:
    name: elasticshift
    labels: 
      name: elasticshift

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticshift

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: elasticshift
  name: elasticshift
rules:
- apiGroups: ["*"]
  resources: ["pods", "deployments", "services", "replicasets", "logs"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: elasticshift
  namespace: elasticshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticshift
subjects:
- kind: User
  name: system:serviceaccount:default:elasticshift
  apiGroup: rbac.authorization.k8s.io