kind: Namespace
apiVersion: v1
metadata:
    name: shiftmk
    labels: 
      name: shiftmk

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shiftmk

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: shiftmk
  name: shiftmk
rules:
- apiGroups: ["*"]
  resources: ["pods", "deployments", "services", "replicasets", "pods/log"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: shiftmk
  namespace: shiftmk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shiftmk
subjects:
- kind: User
  name: system:serviceaccount:default:shiftmk
  apiGroup: rbac.authorization.k8s.io