kind: Namespace
apiVersion: v1
metadata:
    name: elasticshift
    labels: 
      name: elasticshift

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticshift

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: elasticshift
  name: elasticshift
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["deployment"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: shift
  namespace: elasticshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shift
subjects:
- kind: ServiceAccount
  name: shift