kind: Namespace
apiVersion: v1
metadata:
    name: elasticshift
    labels: 
      name: elasticshift

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticshift

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: elasticshift
  name: elasticshift
rules:
- apiGroups: ["apps"]
  resources: ["pods", "deployments", "services"]
  verbs: ["create","delete","get","list","patch","update","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: elasticshift
  namespace: elasticshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticshift
subjects:
- kind: ServiceAccount
  name: elasticshift