apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqlookup 
    role: service
  name: nsqlookup 
spec:
  type: NodePort
  ports:
    - port: 4160
      name: ltcp
      nodePort: 32160
    - port: 4161
      name: lhttp
      nodePort: 32161
  selector:
    name: "nslookup"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqd 
    role: service
  name: nsqd 
spec:
  type: NodePort
  ports:
    - port: 4150
      name: dtcp
      nodePort: 32150
    - port: 4151
      name: dhttp
      nodePort: 32151
  selector:
    name: "nsqd"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: nsqadmin
    role: service
  name: nsqadmin
spec:
  type: NodePort
  ports:
    - port: 4171
      name: ahttp
      nodePort: 31151
  selector:
    name: "nsqadmin"